# Speaker Diarization Configuration
# Settings for pyannote.audio speaker diarization pipeline

model:
  # Model to use for speaker diarization  
  name: "pyannote/speaker-diarization-3.1"
  use_auth_token: true
  device: "cuda"  # Change from "cpu" to "cuda" for GPU acceleration
  
# Clustering parameters - key for better speaker separation
clustering:
  # Minimum number of speakers to detect (useful for known content like Pokemon)
  min_speakers: 2
  
  # Maximum number of speakers to detect (prevents over-segmentation)
  max_speakers: 30
  
  # Clustering threshold - LOWER values = more speakers detected
  # Default is often 0.7, reducing to 0.4-0.5 for more sensitive detection
  threshold: 0.75
  
  # Method for clustering: "centroid", "complete", "average"
  method: "centroid"

# Voice Activity Detection (VAD) settings
vad:
  # Onset/offset detection thresholds
  min_duration_on: 0.5   # Minimum speech segment duration (seconds)
  min_duration_off: 0.1  # Minimum silence duration (seconds)
  
# Segmentation settings  
segmentation:
  # Speech/non-speech segmentation parameters
  speech_threshold: 0.5    # Confidence threshold for speech detection
  min_segment_length: 0.5  # Minimum segment length in seconds
  
# Post-processing
post_processing:
  # Merge segments from same speaker if gap is smaller than this (seconds)
  merge_threshold: 1
  
  # Remove segments shorter than this (seconds)  
  min_segment_duration: 0.2
  
  # Apply smoothing to speaker boundaries
  apply_smoothing: true

# Quality settings
quality:
  # Audio preprocessing for diarization
  sample_rate: 16000  # Required by pyannote
  normalize_audio: true
  
  # Expected speaker characteristics for Pokemon episodes
  expected_speakers:
    - name: "main_characters"
      count: 3  # Ash, Misty, Brock
      voice_type: "young"
    - name: "team_rocket" 
      count: 3  # Jessie, James, Meowth
      voice_type: "adult"
    - name: "narrator"
      count: 1
      voice_type: "adult_male"
    - name: "pokemon_voices"
      count: 1-3  # Pikachu and other Pokemon
      voice_type: "synthetic"

# Debugging and analysis
debug:
  # Save intermediate results for analysis
  save_clustering_plots: false
  save_embedding_plots: false
  verbose_logging: true
  
  # Export speaker embeddings for manual analysis
  export_embeddings: false

# Progress tracking
progress:
  show_progress: true
  log_every_n_files: 1

# Performance settings - CUDA optimizations
performance:
  # Parallel processing workers
  num_workers: 4
  pin_memory: true
  non_blocking: true

# Audio preprocessing
preprocessing:
  target_sample_rate: 16000  # Standard for speech processing

# Batch size
batch_size: 4   # Increase from 1 for better GPU utilization 