# Voice Clustering Configuration
# Optimized for Pokemon anime character voice separation - FIXED CLUSTER APPROACH

embedding:
  # Voice embedding model for speaker verification
  model: "speechbrain/spkrec-ecapa-voxceleb"  # Pre-trained speaker embedding model
  # consider using model: "microsoft/wavlm-base-plus-sv"  # WavLM model, better for speaker verification

  device: "cuda"  # Use GPU if available, fallback to CPU
  normalize: true  # Normalize embeddings for better clustering
  max_audio_length: 10.0  # Maximum seconds per segment for embedding extraction
  min_audio_length: 3.0   # INCREASED - filter very short clips (was 2.0)

clustering:
  # Clustering algorithm and parameters - CONSERVATIVE SEPARATION
  algorithm: "dbscan"          # Switch to DBSCAN for more precise separation
  
  # Hierarchical clustering parameters - BACKUP
  n_clusters: 25               # Much higher if hierarchical is used
  linkage: "ward"              # Linkage method for hierarchical clustering
  
  # DBSCAN parameters - MODERATE SEPARATION (less data loss)
  eps: 0.35                    # Slightly higher - capture more similar voices
  min_samples: 8               # Lower requirement - include more segments
  distance_metric: "cosine"    # Distance metric for voice embeddings

quality:
  # Quality filters for meaningful clusters - MORE PERMISSIVE FOR SMALLER CLUSTERS
  min_cluster_duration: 30.0    # Lower duration requirement 
  min_episodes_per_cluster: 3   # Fewer episodes required
  min_segments_per_cluster: 10  # Lower segment count for more clusters
  purity_threshold: 0.4         # More permissive purity

character_assignment:
  # Character assignment and validation - IMPROVED SENSITIVITY
  use_text_analysis: true       # Use transcript text for character hints
  min_confidence: 0.3           # Lower confidence threshold for more assignments
  
  # Expected Pokemon characters - CORE MAIN CHARACTERS ONLY
  pokemon_characters:
    - "ash"           # Main protagonist (most dialogue)
    - "misty"         # Main character 
    - "brock"         # Main character
    - "jessie"        # Team Rocket (frequent recurring)
    - "james"         # Team Rocket (frequent recurring)
    - "meowth"        # Team Rocket (frequent recurring)
    - "narrator"      # Common across episodes
    - "pokédex"       # Common across episodes

text_analysis:
  # Text-based character hints (optional enhancement)
  enabled: true
  
  # Character-specific phrases and patterns
  character_hints:
    ash:
      - "pikachu"
      - "i choose you"
    
    narrator:
      - "our heroes"
      - "our hero"
      - "meanwhile"
      - "to be continued"
      - "pokemon trainer"
      - "ash and"
    
    jessie:
      - "prepare for trouble"
      - "team rocket"
      - "beauty"
      - "jessie"
    
    james:
      - "make it double"
      - "team rocket"
      - "wobbuffet"
      - "james"
    
    meowth:
      - "that's right"
      - "team rocket"
      - "da boss"
      - "meowth"
      - "surrender now"
    
    announcer:
      - "ladies and gentlemen"
      - "trainer"
      - "battle"
      - "gym leader"

processing:
  # Processing optimization
  parallel_workers: 3          # Number of parallel workers for embedding extraction
  batch_size: 16              # Batch size for embedding model inference
  cache_embeddings: true      # Cache embeddings for faster re-runs
  memory_limit_gb: 4          # Memory limit for processing (prevent OOM)
  
  # VERY RELAXED FILTERING FOR FIXED CLUSTERS
  filter_minor_characters: false  # DON'T filter - let content analysis decide
  max_clusters: 15            # MATCH n_clusters
  merge_similar_threshold: 0.7 # Merge threshold
  ignore_noise_clusters: false # Keep all clusters for analysis

output:
  # Output configuration
  save_embeddings: true       # Save voice embeddings for analysis
  save_cluster_samples: true  # Save representative audio samples per cluster
  generate_report: true       # Generate detailed clustering report
  create_character_dirs: true # Create character-specific directories

validation:
  # Validation and quality checks
  cross_validate: true        # Perform cross-validation on clusters
  silhouette_analysis: true   # Compute silhouette scores for cluster quality
  manual_review_threshold: 0.5 # Flag clusters below this confidence for manual review 